apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deploy.yml
- service.yml

images:
- name: node-api
  newName: igorlage/schedeasy-simple-api
  newTag: 9df059245e8247da3e7cfe6b3b29942910c7b829
