apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deploy.yml
- service.yml

images:
- name: node-api
  newName: igorlage/schedeasy-simple-api
  newTag: 92a9ab841223164d9aa01c04d0ecf7c220b67252
