apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deploy.yml
- service.yml

images:
- name: node-api
  newName: igorlage/schedeasy-simple-api
  newTag: 582a2cc371f9862525f6fa5c3b775b4d73e9ee25
